// Copyright (c) 2016 by Richard A. Wilkes. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, version 2.0. If a copy of the MPL was not distributed with
// this file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// This Source Code Form is "Incompatible With Secondary Licenses", as
// defined by the Mozilla Public License, version 2.0.

package ui

import "strings"

// CSS named colors.
var (
	AliceBlueColor            = RGB(240, 248, 255)
	AntiqueWhiteColor         = RGB(250, 235, 215)
	AquaColor                 = RGB(0, 255, 255)
	AquamarineColor           = RGB(127, 255, 212)
	AzureColor                = RGB(240, 255, 255)
	BeigeColor                = RGB(245, 245, 220)
	BisqueColor               = RGB(255, 228, 196)
	BlackColor                = RGB(0, 0, 0)
	BlanchedAlmondColor       = RGB(255, 235, 205)
	BlueColor                 = RGB(0, 0, 255)
	BlueVioletColor           = RGB(138, 43, 226)
	BrownColor                = RGB(165, 42, 42)
	BurlyWoodColor            = RGB(222, 184, 135)
	CadetBlueColor            = RGB(95, 158, 160)
	ChartreuseColor           = RGB(127, 255, 0)
	ChocolateColor            = RGB(210, 105, 30)
	CoralColor                = RGB(255, 127, 80)
	CornflowerBlueColor       = RGB(100, 149, 237)
	CornsilkColor             = RGB(255, 248, 220)
	CrimsonColor              = RGB(220, 20, 60)
	CyanColor                 = RGB(0, 255, 255)
	DarkBlueColor             = RGB(0, 0, 139)
	DarkCyanColor             = RGB(0, 139, 139)
	DarkGoldenRodColor        = RGB(184, 134, 11)
	DarkGrayColor             = RGB(169, 169, 169)
	DarkGreenColor            = RGB(0, 100, 0)
	DarkGreyColor             = RGB(169, 169, 169)
	DarkKhakiColor            = RGB(189, 183, 107)
	DarkMagentaColor          = RGB(139, 0, 139)
	DarkOliveGreenColor       = RGB(85, 107, 47)
	DarkOrangeColor           = RGB(255, 140, 0)
	DarkOrchidColor           = RGB(153, 50, 204)
	DarkRedColor              = RGB(139, 0, 0)
	DarkSalmonColor           = RGB(233, 150, 122)
	DarkSeaGreenColor         = RGB(143, 188, 143)
	DarkSlateBlueColor        = RGB(72, 61, 139)
	DarkSlateGrayColor        = RGB(47, 79, 79)
	DarkSlateGreyColor        = RGB(47, 79, 79)
	DarkTurquoiseColor        = RGB(0, 206, 209)
	DarkVioletColor           = RGB(148, 0, 211)
	DeepPinkColor             = RGB(255, 20, 147)
	DeepSkyBlueColor          = RGB(0, 191, 255)
	DimGrayColor              = RGB(105, 105, 105)
	DimGreyColor              = RGB(105, 105, 105)
	DodgerBlueColor           = RGB(30, 144, 255)
	FireBrickColor            = RGB(178, 34, 34)
	FloralWhiteColor          = RGB(255, 250, 240)
	ForestGreenColor          = RGB(34, 139, 34)
	FuchsiaColor              = RGB(255, 0, 255)
	GainsboroColor            = RGB(220, 220, 220)
	GhostWhiteColor           = RGB(248, 248, 255)
	GoldColor                 = RGB(255, 215, 0)
	GoldenRodColor            = RGB(218, 165, 32)
	GrayColor                 = RGB(128, 128, 128)
	GreenColor                = RGB(0, 128, 0)
	GreenYellowColor          = RGB(173, 255, 47)
	GreyColor                 = RGB(128, 128, 128)
	HoneyDewColor             = RGB(240, 255, 240)
	HotPinkColor              = RGB(255, 105, 180)
	IndianRedColor            = RGB(205, 92, 92)
	IndigoColor               = RGB(75, 0, 130)
	IvoryColor                = RGB(255, 255, 240)
	KhakiColor                = RGB(240, 230, 140)
	LavenderColor             = RGB(230, 230, 250)
	LavenderBlushColor        = RGB(255, 240, 245)
	LawnGreenColor            = RGB(124, 252, 0)
	LemonChiffonColor         = RGB(255, 250, 205)
	LightBlueColor            = RGB(173, 216, 230)
	LightCoralColor           = RGB(240, 128, 128)
	LightCyanColor            = RGB(224, 255, 255)
	LightGoldenRodYellowColor = RGB(250, 250, 210)
	LightGrayColor            = RGB(211, 211, 211)
	LightGreenColor           = RGB(144, 238, 144)
	LightGreyColor            = RGB(211, 211, 211)
	LightPinkColor            = RGB(255, 182, 193)
	LightSalmonColor          = RGB(255, 160, 122)
	LightSeaGreenColor        = RGB(32, 178, 170)
	LightSkyBlueColor         = RGB(135, 206, 250)
	LightSlateGrayColor       = RGB(119, 136, 153)
	LightSlateGreyColor       = RGB(119, 136, 153)
	LightSteelBlueColor       = RGB(176, 196, 222)
	LightYellowColor          = RGB(255, 255, 224)
	LimeColor                 = RGB(0, 255, 0)
	LimeGreenColor            = RGB(50, 205, 50)
	LinenColor                = RGB(250, 240, 230)
	MagentaColor              = RGB(255, 0, 255)
	MaroonColor               = RGB(128, 0, 0)
	MediumAquaMarineColor     = RGB(102, 205, 170)
	MediumBlueColor           = RGB(0, 0, 205)
	MediumOrchidColor         = RGB(186, 85, 211)
	MediumPurpleColor         = RGB(147, 112, 219)
	MediumSeaGreenColor       = RGB(60, 179, 113)
	MediumSlateBlueColor      = RGB(123, 104, 238)
	MediumSpringGreenColor    = RGB(0, 250, 154)
	MediumTurquoiseColor      = RGB(72, 209, 204)
	MediumVioletRedColor      = RGB(199, 21, 133)
	MidnightBlueColor         = RGB(25, 25, 112)
	MintCreamColor            = RGB(245, 255, 250)
	MistyRoseColor            = RGB(255, 228, 225)
	MoccasinColor             = RGB(255, 228, 181)
	NavajoWhiteColor          = RGB(255, 222, 173)
	NavyColor                 = RGB(0, 0, 128)
	OldLaceColor              = RGB(253, 245, 230)
	OliveColor                = RGB(128, 128, 0)
	OliveDrabColor            = RGB(107, 142, 35)
	OrangeColor               = RGB(255, 165, 0)
	OrangeRedColor            = RGB(255, 69, 0)
	OrchidColor               = RGB(218, 112, 214)
	PaleGoldenRodColor        = RGB(238, 232, 170)
	PaleGreenColor            = RGB(152, 251, 152)
	PaleTurquoiseColor        = RGB(175, 238, 238)
	PaleVioletRedColor        = RGB(219, 112, 147)
	PapayaWhipColor           = RGB(255, 239, 213)
	PeachPuffColor            = RGB(255, 218, 185)
	PeruColor                 = RGB(205, 133, 63)
	PinkColor                 = RGB(255, 192, 203)
	PlumColor                 = RGB(221, 160, 221)
	PowderBlueColor           = RGB(176, 224, 230)
	PurpleColor               = RGB(128, 0, 128)
	RedColor                  = RGB(255, 0, 0)
	RosyBrownColor            = RGB(188, 143, 143)
	RoyalBlueColor            = RGB(65, 105, 225)
	SaddleBrownColor          = RGB(139, 69, 19)
	SalmonColor               = RGB(250, 128, 114)
	SandyBrownColor           = RGB(244, 164, 96)
	SeaGreenColor             = RGB(46, 139, 87)
	SeaShellColor             = RGB(255, 245, 238)
	SiennaColor               = RGB(160, 82, 45)
	SilverColor               = RGB(192, 192, 192)
	SkyBlueColor              = RGB(135, 206, 235)
	SlateBlueColor            = RGB(106, 90, 205)
	SlateGrayColor            = RGB(112, 128, 144)
	SlateGreyColor            = RGB(112, 128, 144)
	SnowColor                 = RGB(255, 250, 250)
	SpringGreenColor          = RGB(0, 255, 127)
	SteelBlueColor            = RGB(70, 130, 180)
	TanColor                  = RGB(210, 180, 140)
	TealColor                 = RGB(0, 128, 128)
	ThistleColor              = RGB(216, 191, 216)
	TomatoColor               = RGB(255, 99, 71)
	TurquoiseColor            = RGB(64, 224, 208)
	VioletColor               = RGB(238, 130, 238)
	WheatColor                = RGB(245, 222, 179)
	WhiteColor                = RGB(255, 255, 255)
	WhiteSmokeColor           = RGB(245, 245, 245)
	YellowColor               = RGB(255, 255, 0)
	YellowGreenColor          = RGB(154, 205, 50)
	nameToColor               = make(map[string]Color)
	colorToName               = make(map[Color]string)
)

func init() {
	register("AliceBlue", AliceBlueColor)
	register("AntiqueWhite", AntiqueWhiteColor)
	register("Aqua", AquaColor)
	register("Aquamarine", AquamarineColor)
	register("Azure", AzureColor)
	register("Beige", BeigeColor)
	register("Bisque", BisqueColor)
	register("Black", BlackColor)
	register("BlanchedAlmond", BlanchedAlmondColor)
	register("Blue", BlueColor)
	register("BlueViolet", BlueVioletColor)
	register("Brown", BrownColor)
	register("BurlyWood", BurlyWoodColor)
	register("CadetBlue", CadetBlueColor)
	register("Chartreuse", ChartreuseColor)
	register("Chocolate", ChocolateColor)
	register("Coral", CoralColor)
	register("CornflowerBlue", CornflowerBlueColor)
	register("Cornsilk", CornsilkColor)
	register("Crimson", CrimsonColor)
	register("Cyan", CyanColor)
	register("DarkBlue", DarkBlueColor)
	register("DarkCyan", DarkCyanColor)
	register("DarkGoldenRod", DarkGoldenRodColor)
	register("DarkGray", DarkGrayColor)
	register("DarkGreen", DarkGreenColor)
	register("DarkGrey", DarkGreyColor)
	register("DarkKhaki", DarkKhakiColor)
	register("DarkMagenta", DarkMagentaColor)
	register("DarkOliveGreen", DarkOliveGreenColor)
	register("DarkOrange", DarkOrangeColor)
	register("DarkOrchid", DarkOrchidColor)
	register("DarkRed", DarkRedColor)
	register("DarkSalmon", DarkSalmonColor)
	register("DarkSeaGreen", DarkSeaGreenColor)
	register("DarkSlateBlue", DarkSlateBlueColor)
	register("DarkSlateGray", DarkSlateGrayColor)
	register("DarkSlateGrey", DarkSlateGreyColor)
	register("DarkTurquoise", DarkTurquoiseColor)
	register("DarkViolet", DarkVioletColor)
	register("DeepPink", DeepPinkColor)
	register("DeepSkyBlue", DeepSkyBlueColor)
	register("DimGray", DimGrayColor)
	register("DimGrey", DimGreyColor)
	register("DodgerBlue", DodgerBlueColor)
	register("FireBrick", FireBrickColor)
	register("FloralWhite", FloralWhiteColor)
	register("ForestGreen", ForestGreenColor)
	register("Fuchsia", FuchsiaColor)
	register("Gainsboro", GainsboroColor)
	register("GhostWhite", GhostWhiteColor)
	register("Gold", GoldColor)
	register("GoldenRod", GoldenRodColor)
	register("Gray", GrayColor)
	register("Green", GreenColor)
	register("GreenYellow", GreenYellowColor)
	register("Grey", GreyColor)
	register("HoneyDew", HoneyDewColor)
	register("HotPink", HotPinkColor)
	register("IndianRed", IndianRedColor)
	register("Indigo", IndigoColor)
	register("Ivory", IvoryColor)
	register("Khaki", KhakiColor)
	register("Lavender", LavenderColor)
	register("LavenderBlush", LavenderBlushColor)
	register("LawnGreen", LawnGreenColor)
	register("LemonChiffon", LemonChiffonColor)
	register("LightBlue", LightBlueColor)
	register("LightCoral", LightCoralColor)
	register("LightCyan", LightCyanColor)
	register("LightGoldenRodYellow", LightGoldenRodYellowColor)
	register("LightGray", LightGrayColor)
	register("LightGreen", LightGreenColor)
	register("LightGrey", LightGreyColor)
	register("LightPink", LightPinkColor)
	register("LightSalmon", LightSalmonColor)
	register("LightSeaGreen", LightSeaGreenColor)
	register("LightSkyBlue", LightSkyBlueColor)
	register("LightSlateGray", LightSlateGrayColor)
	register("LightSlateGrey", LightSlateGreyColor)
	register("LightSteelBlue", LightSteelBlueColor)
	register("LightYellow", LightYellowColor)
	register("Lime", LimeColor)
	register("LimeGreen", LimeGreenColor)
	register("Linen", LinenColor)
	register("Magenta", MagentaColor)
	register("Maroon", MaroonColor)
	register("MediumAquaMarine", MediumAquaMarineColor)
	register("MediumBlue", MediumBlueColor)
	register("MediumOrchid", MediumOrchidColor)
	register("MediumPurple", MediumPurpleColor)
	register("MediumSeaGreen", MediumSeaGreenColor)
	register("MediumSlateBlue", MediumSlateBlueColor)
	register("MediumSpringGreen", MediumSpringGreenColor)
	register("MediumTurquoise", MediumTurquoiseColor)
	register("MediumVioletRed", MediumVioletRedColor)
	register("MidnightBlue", MidnightBlueColor)
	register("MintCream", MintCreamColor)
	register("MistyRose", MistyRoseColor)
	register("Moccasin", MoccasinColor)
	register("NavajoWhite", NavajoWhiteColor)
	register("Navy", NavyColor)
	register("OldLace", OldLaceColor)
	register("Olive", OliveColor)
	register("OliveDrab", OliveDrabColor)
	register("Orange", OrangeColor)
	register("OrangeRed", OrangeRedColor)
	register("Orchid", OrchidColor)
	register("PaleGoldenRod", PaleGoldenRodColor)
	register("PaleGreen", PaleGreenColor)
	register("PaleTurquoise", PaleTurquoiseColor)
	register("PaleVioletRed", PaleVioletRedColor)
	register("PapayaWhip", PapayaWhipColor)
	register("PeachPuff", PeachPuffColor)
	register("Peru", PeruColor)
	register("Pink", PinkColor)
	register("Plum", PlumColor)
	register("PowderBlue", PowderBlueColor)
	register("Purple", PurpleColor)
	register("Red", RedColor)
	register("RosyBrown", RosyBrownColor)
	register("RoyalBlue", RoyalBlueColor)
	register("SaddleBrown", SaddleBrownColor)
	register("Salmon", SalmonColor)
	register("SandyBrown", SandyBrownColor)
	register("SeaGreen", SeaGreenColor)
	register("SeaShell", SeaShellColor)
	register("Sienna", SiennaColor)
	register("Silver", SilverColor)
	register("SkyBlue", SkyBlueColor)
	register("SlateBlue", SlateBlueColor)
	register("SlateGray", SlateGrayColor)
	register("SlateGrey", SlateGreyColor)
	register("Snow", SnowColor)
	register("SpringGreen", SpringGreenColor)
	register("SteelBlue", SteelBlueColor)
	register("Tan", TanColor)
	register("Teal", TealColor)
	register("Thistle", ThistleColor)
	register("Tomato", TomatoColor)
	register("Turquoise", TurquoiseColor)
	register("Violet", VioletColor)
	register("Wheat", WheatColor)
	register("White", WhiteColor)
	register("WhiteSmoke", WhiteSmokeColor)
	register("Yellow", YellowColor)
	register("YellowGreen", YellowGreenColor)
}

func register(name string, color Color) {
	nameToColor[strings.ToLower(name)] = color
	colorToName[color] = name
}
